# SPDX-License-Identifier: GPL-2.0
robin-vkms-y := 	\
	robin_vkms_drv.o \
	robin_vkms_plane.o \
	robin_vkms_output.o \
	robin_vkms_crtc.o \
	robin_vkms_composer.o \
	robin_vkms_writeback.o

# obj-m += robin-vkms.o